# created by init task for use with github actons
workspaces:
  - name: default
    path: ./
secrets:
  auth:
    approle:
      role: vault_policy_scaffolding
  kv:
    - path: secret/azure/sp/infra
